### ISSUE TITLE
Flow past rod case towards figure

### ISSUE THREAD

**Issue by armantekinalp** [SophT-Team/SophT-Simulator#55]
TODO list:

- [x] Run cases with resolution nx=196, nx=384 with flow speed 1.1 m/s.
- [x] Probe experimental data for theta.
- [x] Make validation plot
- [x] Dump hdf5 data for rendering at nx=256, flow speed 1.1 m/s.
- [x] Convergence plot using forces.
- [x] Paraview image
- [x] Combine in illustrator

**Comment by bhosale2** [comment]
@armantekinalp please post the final image here and close the issue.

**Comment by armantekinalp** [comment]
![3d_rod_validation_figure-light-01](https://user-images.githubusercontent.com/53585636/205813529-408c9b0f-883e-4977-85a0-95294279de1c.png)
