### ISSUE TITLE
Flow past sphere towards figure

### ISSUE THREAD

**Issue by armantekinalp** [SophT-Team/SophT-Simulator#56]
TODO list:

- [x] Compute Eddy length for Re 25, 50, 100, 200
- [x] Drag validation (if possible eddy length) figure
- [x] Convergence figure
- [x] Shedding Re 400
- [x] hdf5 data for Re 100, for resolution nx 256
- [x] Paraview image
- [x] Combine in illustrator

**Comment by bhosale2** [comment]
@armantekinalp please post the final image here and close the issue.

**Comment by armantekinalp** [comment]
![3d_rod_validation_figure-light-01](https://user-images.githubusercontent.com/53585636/205813252-e0bd5047-715b-43e5-aa4b-692f583e22ec.png)

**Comment by armantekinalp** [comment]
![3d_sphere_validation_figure-light-01](https://user-images.githubusercontent.com/53585636/205813368-d1472382-0d3a-4753-8564-38fb50d17b47.png)
