### ISSUE TITLE
Reset boundaries for vorticity stretching and laplacian filter 3d kernel

### ISSUE THREAD

**Issue by fankiat** [SophT-Team/SophT-Simulator#90]
These kernels are currently not equipped with `reset_ghost_zone` feature. I can submit a PR for this.

**Comment by bhosale2** [comment]
I don't think this issue in its current form requires resolution:

1. Vorticity stretching approach doesn't work out numerically. In fact, please check the example cases to see what we actually use for the advection term, in order to avoid coding up unnecessary kernels. Soon I will remove the stretching option from the simulator altogether, hence we don't need this correction.
2. For the laplacian filter kernel is this option needed for the mpi side?

**Comment by fankiat** [comment]
@bhosale2 Maybe partially it might.

1. I see. Sorry I did not notice this earlier. I thought we were using them, should've paid more attention to the kernels employed in the simulator and examples.
2. Yeah, initially I thought I would need it for the MPI side. After reading your comments, I think maybe you are right. In that case, the kernel would operate correctly in the inner cell (i.e. exclude ghost cell) and we will still get the correct resulting inner cell. Proceeding in the solver algorithm, we would call other kernels like compute flow velocity which in itself that kernel would ghost the inner relevant field as currently set up in `sopht-mpi`, so perhaps we won't run into an issue after all. Please confirm that my thought process is correct.

Again, sorry for the premature PR without prior discussion.

**Comment by fankiat** [comment]
Hmm.. on second thought, for the laplacian filter, the boundary clearing may behave differently in the mpi context, since the boundary clearing is set to 1 cell here, while the mpi local domain has `ghost_size` typically set to 2, this means that the result may still be looking at different results if we use the kernel as is, right? Unless we are expecting `sopht-mpi` to adjust for this offset, but I'm not sure if that is the best workaround. What do you think @bhosale2 ?

**Comment by bhosale2** [comment]
An option to set a custom boundary clearing zone for the laplacian filter is added in 78af5ee. With this, I will now close the issue and corresponding PR.
